Repository CambioML/CambioML.github.io, pull requests merged in 2025-06, with the labels that each got.

#347 Refactor frontend
  app/[locale]/account/page.tsx
  app/[locale]/login/PasswordStrength.tsx
  app/[locale]/login/amplify.ts
  app/[locale]/login/login.css
  app/[locale]/login/page.tsx
  app/actions/account/getApiKeysForUser.ts
  app/actions/account/getNewApiKey.ts
  app/actions/getUserData.ts
  app/actions/updateQuota.ts
  app/components/account/AccountPageContainer.tsx
  app/components/account/ApiKeyRow.tsx
  app/components/account/BuyCreditsButton.tsx
  app/components/auth/LoginButton.tsx
  app/components/auth/LogoutButton.tsx
  app/components/inputs/CheckboxField.tsx
  app/components/playground/MarkdownExtractContainer.tsx
  app/components/playground/ProductionContext.tsx
  app/components/pricing/PortalButton.tsx
  app/components/providers/AmplifyAuthProvider.tsx
  app/hooks/useAccountStore.ts
  app/hooks/useAmplifyAuth.ts
  app/hooks/usePopupAuth.ts
  app/hooks/useUserProfile.ts
  app/layout.tsx
  app/payment/cancelled/page.tsx
  app/payment/success/page.tsx
  bun.lock
  lib/translations/ar.ts
  lib/translations/cs.ts
  lib/translations/da.ts
  lib/translations/de.ts
  lib/translations/en.ts
  lib/translations/es.ts
  lib/translations/fi.ts
  lib/translations/fr.ts
  lib/translations/hi.ts
  lib/translations/hu.ts
  lib/translations/it.ts
  lib/translations/ja.ts
  lib/translations/ko.ts
  lib/translations/nl.ts
  lib/translations/no.ts
  lib/translations/pl.ts
  lib/translations/pt.ts
  lib/translations/ro.ts
  lib/translations/ru.ts
  lib/translations/sv.ts
  lib/translations/tr.ts
  lib/translations/zh.ts
  package-lock.json
  package.json
  scripts/i18n-ai-translator.ts
Labels: Review effort 4/5

#350 Revert "Refactor frontend"
  app/[locale]/account/page.tsx
  app/[locale]/login/PasswordStrength.tsx
  app/[locale]/login/amplify.ts
  app/[locale]/login/login.css
  app/[locale]/login/page.tsx
  app/actions/account/getApiKeysForUser.ts
  app/actions/account/getNewApiKey.ts
  app/actions/getUserData.ts
  app/actions/updateQuota.ts
  app/components/account/AccountPageContainer.tsx
  app/components/account/ApiKeyRow.tsx
  app/components/account/BuyCreditsButton.tsx
  app/components/auth/LoginButton.tsx
  app/components/auth/LogoutButton.tsx
  app/components/inputs/CheckboxField.tsx
  app/components/playground/MarkdownExtractContainer.tsx
  app/components/playground/ProductionContext.tsx
  app/components/pricing/PortalButton.tsx
  app/components/providers/AmplifyAuthProvider.tsx
  app/hooks/useAccountStore.ts
  app/hooks/useAmplifyAuth.ts
  app/hooks/usePopupAuth.ts
  app/hooks/useUserProfile.ts
  app/layout.tsx
  app/payment/cancelled/page.tsx
  app/payment/success/page.tsx
  bun.lock
  lib/translations/ar.ts
  lib/translations/cs.ts
  lib/translations/da.ts
  lib/translations/de.ts
  lib/translations/en.ts
  lib/translations/es.ts
  lib/translations/fi.ts
  lib/translations/fr.ts
  lib/translations/hi.ts
  lib/translations/hu.ts
  lib/translations/it.ts
  lib/translations/ja.ts
  lib/translations/ko.ts
  lib/translations/nl.ts
  lib/translations/no.ts
  lib/translations/pl.ts
  lib/translations/pt.ts
  lib/translations/ro.ts
  lib/translations/ru.ts
  lib/translations/sv.ts
  lib/translations/tr.ts
  lib/translations/zh.ts
  package-lock.json
  package.json
  scripts/i18n-ai-translator.ts
Labels: Review effort 5/5

#354 Blog layout adjustment
  .eslintrc.js
  app/[locale]/blog/[slug]/page.tsx
  app/components/playground/ActionContainer.tsx
  app/components/playground/FilesContainer.tsx
  app/components/playground/PlaygroundContainerForBlog.tsx
  app/components/playground/PlaygroundTab.tsx
  app/components/playground/QATable.tsx
  app/components/playground/QuotaDisplay.tsx
  app/components/playground/ResultContainer.tsx
  app/components/playground/table/MapSchemaCell.tsx
  app/components/playground/table/MapTableSelectContainer.tsx
  app/components/solutions/SolutionsList.tsx
  app/hooks/useAmplifyAuth.ts
  app/hooks/useWindowScroll.ts
  app/layout.tsx
  bun.lock
  package-lock.json
  package.json
Labels: Review effort 3/5
